# ============================================================
# LittleOS with Limine Bootloader - Configuration
# ============================================================

# Waktu tunggu sebelum boot otomatis (dalam detik)
timeout: 5
interface_mode: graphics
wallpaper: boot():/boot/limine/bg.jpg
# ============================================================
# Entri Boot: LittleOS
# ============================================================
/LittleOS Gajah PHP x86
    # Gunakan protokol boot Limine
    protocol: limine
    
    # Biarkan Limine pilih mode grafis terbaik

    # Lokasi file kernel
    path: boot():/boot/kernel
