# ============================================================
# LittleOS with Limine Bootloader - Configuration
# ============================================================

# Waktu tunggu sebelum boot otomatis (dalam detik)
timeout: 5

wallpaper: boot():/boot/limine/limine-wallpaper.jpeg
# ============================================================
# Entri Boot: LittleOS
# ============================================================
/LittleOS Gajah PHP x86

    # Gunakan protokol boot Limine
    protocol: limine
    
    # Biarkan Limine pilih mode grafis terbaik

    # Lokasi file kernel
    path: boot():/boot/littleos
